apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-ventas
  namespace: innovatech
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-ventas
  template:
    metadata:
      labels:
        app: mysql-ventas
    spec:
      containers:
      - name: mysql
        image: mysql:8
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef: { name: ventas-secret, key: MYSQL_ROOT_PASSWORD }
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef: { name: innovatech-config, key: VENTAS_DB_NAME }
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef: { name: ventas-secret, key: SPRING_DATASOURCE_USERNAME }
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef: { name: ventas-secret, key: SPRING_DATASOURCE_PASSWORD }
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
      volumes:
      - name: data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-ventas-service
  namespace: innovatech
spec:
  selector:
    app: mysql-ventas
  ports:
  - port: 3306
    targetPort: 3306
